const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const state={fileData:null,fileType:null,productionConnected:false,sandboxConnected:false,boards:[],pins:[],designerData:null,designerImage:null};
const PAGE_META={dashboard:['Dashboard','Content workspace'],create:['Create','Creative studio'],planner:['Planner','Drafts & queue'],library:['Pin Library','Authorized account'],analytics:['Analytics','Organic reporting'],boards:['Boards','Organize content'],settings:['Settings','Account & safety']};
const STORAGE_KEY='da_studio_workspace_v2';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function compact(v){const n=Number(v||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?Math.round(n/1e3)+'K':String(Math.round(n))}
function formatDate(v){if(!v)return 'No time selected';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function workspace(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"drafts":[]}')}catch{return{drafts:[]}}}
function saveWorkspace(w){localStorage.setItem(STORAGE_KEY,JSON.stringify(w))}
async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function show(name){$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$$('.page').forEach(p=>p.classList.remove('active'));$('#page-'+name)?.classList.add('active');const meta=PAGE_META[name]||[name,''];$('#pageTitle').textContent=meta[0];$('#pageSubtitle').textContent=meta[1];$('.sidebar').classList.remove('open');if(name==='analytics')loadAnalytics();if(name==='create')loadStatus();if(name==='planner')renderPlanner();if(name==='library')loadPins();if(name==='boards')loadBoards()}
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');

async function loadStatus(){try{const s=await api('/api/pinterest?action=status');state.productionConnected=!!s.productionConnected;state.sandboxConnected=!!s.sandboxConnected;$('#connectionDot').classList.toggle('on',state.productionConnected);$('#connectionText').textContent=state.productionConnected?'Connected':'Not connected';const n=$('#createNotice');if(state.productionConnected){n.className='notice success';n.textContent='Pinterest is connected with Standard access. Choose one Board and one Pin to publish.';await loadBoards(true)}else{n.className='notice';n.textContent='Connect Pinterest to load your Boards and publish.';$('#board').innerHTML='<option value="">Connect Pinterest first…</option>';$('#publish').disabled=true}}catch(e){$('#connectionText').textContent='Connection unavailable';$('#publish').disabled=true}}
async function loadAccount(){try{const d=await api('/api/pinterest?action=account');const label=d.account?.username?'@'+d.account.username:'Connected';$('#accountLabel').textContent=label;$('#connectionText').textContent=label;$('#connectionDot').classList.add('on')}catch{$('#accountLabel').textContent='Not connected'}}

async function loadAnalytics(){const n=$('#analyticsNotice');n.className='notice';n.textContent='Loading authorized analytics…';try{const d=await api('/api/pinterest?action=analytics');const m=d.summary||{};for(const [id,key] of [['metricImpressions','IMPRESSION'],['metricSaves','SAVE'],['metricClicks','PIN_CLICK'],['metricOutbound','OUTBOUND_CLICK'],['dashImpressions','IMPRESSION'],['dashSaves','SAVE'],['dashClicks','PIN_CLICK'],['dashOutbound','OUTBOUND_CLICK']]){const el=$('#'+id);if(el)el.textContent=compact(m[key])}$('#topPins').innerHTML=(d.topPins||[]).map(p=>'<tr><td>'+esc(p.pin_id||'—')+'</td><td>'+compact(p.metrics?.IMPRESSION)+'</td><td>'+compact(p.metrics?.SAVE)+'</td><td>'+compact(p.metrics?.PIN_CLICK)+'</td><td>'+compact(p.metrics?.OUTBOUND_CLICK)+'</td></tr>').join('')||'<tr><td colspan="5">Pinterest returned no Top Pins for this range.</td></tr>';n.className='notice success';n.textContent='Live organic analytics loaded from Pinterest for the authorized account.';return true}catch(e){n.className='notice';n.textContent=e.message||'Pinterest analytics are unavailable.';return false}}
$('#refreshAnalytics').onclick=loadAnalytics;

async function loadBoards(silent=false){const notice=$('#boardNotice');try{const d=await api('/api/pinterest?action=boards');state.boards=d.boards||[];$('#board').innerHTML=state.boards.map(b=>'<option value="'+esc(b.id)+'">'+esc(b.name||b.id)+'</option>').join('')||'<option value="">No Boards returned</option>';$('#publish').disabled=!state.boards.length;$('#boardCount').textContent=String(state.boards.length);$('#boardList').innerHTML=state.boards.map(b=>'<div class="board-item"><div><strong>'+esc(b.name||'Untitled Board')+'</strong><small>'+esc(b.id||'')+'</small></div><span class="count-pill">Board</span></div>').join('')||'<div class="empty-state">No Boards returned by Pinterest.</div>';if(!silent){notice.className='notice success';notice.textContent='Boards loaded from the authorized Pinterest account.'}}catch(e){$('#boardList').innerHTML='<div class="empty-state">'+esc(e.message||'Could not load Boards.')+'</div>';if(!silent){notice.className='notice';notice.textContent=e.message||'Could not load Boards.'}}}
$('#refreshBoards').onclick=()=>loadBoards(false);
$('#createBoard').onclick=async()=>{const name=$('#newBoardName').value.trim(),description=$('#newBoardDescription').value.trim(),n=$('#boardNotice');if(!name){n.className='notice';n.textContent='Enter a Board name first.';return}if(!confirm('Create this user-selected Board on the connected Pinterest account?'))return;n.className='notice';n.textContent='Creating the selected Board…';try{const d=await api('/api/pinterest?action=create-board',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});n.className='notice success';n.textContent='Board created successfully: '+(d.board?.name||name);$('#newBoardName').value='';$('#newBoardDescription').value='';await loadBoards(true)}catch(e){n.className='notice';n.textContent=e.message||'Could not create Board.'}};

function pinImage(p){return p?.media?.images?.['600x']?.url||p?.media?.images?.['400x300']?.url||p?.media?.images?.originals?.url||p?.media?.image_cover_url||''}
async function loadPins(){const n=$('#libraryNotice');n.className='notice';n.textContent='Loading your Pins from Pinterest…';try{const d=await api('/api/pinterest?action=pins');state.pins=d.pins||[];$('#pinGrid').innerHTML=state.pins.map(p=>{const img=pinImage(p),style=img?' style="background-image:url(\''+esc(img)+'\')"':'';return '<article class="pin-card"><div class="pin-thumb"'+style+'>'+(!img?'Pinterest Pin':'')+'</div><h3>'+esc(p.title||'Untitled Pin')+'</h3><p>'+esc((p.description||'').slice(0,150))+'</p><div class="pin-meta"><span>'+esc(p.id||'')+'</span><span>'+esc(p.created_at?new Date(p.created_at).toLocaleDateString():'')+'</span></div><div class="pin-actions"><a class="mini" href="https://www.pinterest.com/pin/'+encodeURIComponent(String(p.id||''))+'/" target="_blank" rel="noopener">View on Pinterest</a>'+(p.link?'<a class="mini" href="'+esc(p.link)+'" target="_blank" rel="noopener">Destination</a>':'')+'<button class="mini danger" data-delete-pin="'+esc(p.id)+'">Delete</button></div></article>'}).join('')||'<div class="empty-state">Pinterest returned no Pins.</div>';$$('[data-delete-pin]').forEach(b=>b.onclick=()=>deletePin(b.dataset.deletePin));n.className='notice success';n.textContent='Loaded '+state.pins.length+' Pins directly from Pinterest. No library copy is stored by Decor Areas Studio.'}catch(e){n.className='notice';n.textContent=e.message||'Could not load Pins.';$('#pinGrid').innerHTML='<div class="empty-state">Connect Pinterest to load your Pin library.</div>'}}
async function deletePin(id){if(!id||!confirm('Delete this specific Pin from Pinterest? This action cannot be undone in Decor Areas Studio.'))return;try{await api('/api/pinterest?action=delete-pin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin_id:id})});await loadPins()}catch(e){alert(e.message||'Could not delete Pin')}}
$('#refreshPins').onclick=loadPins;

function updatePreview(){const t=$('#title').value.trim(),d=$('#description').value.trim(),u=$('#destination').value.trim();$('#previewTitle').textContent=t||'Your title';$('#previewDescription').textContent=d||'Your description will appear here.';$('#previewLink').textContent=u||'Destination link'}
$('#title').oninput=updatePreview;$('#description').oninput=updatePreview;$('#destination').oninput=updatePreview;
$('#imageFile').onchange=()=>{const f=$('#imageFile').files[0];if(!f)return;readImageFile(f,true)};
function readImageFile(f,setPreview){if(!['image/jpeg','image/png','image/webp'].includes(f.type)){alert('Use JPG, PNG or WebP.');return}if(f.size>8*1024*1024){alert('Use an image under 8 MB for this upload.');return}const r=new FileReader();r.onload=()=>{const data=String(r.result),i=data.indexOf(',');state.fileData=data.slice(i+1);state.fileType=f.type;if(setPreview){$('#preview').style.backgroundImage='url("'+data+'")';$('#preview').innerHTML=''}};r.readAsDataURL(f)}

$('#publish').onclick=async()=>{const n=$('#publishNotice');if(!state.productionConnected){n.className='notice';n.textContent='Connect Pinterest before publishing.';return}if(!$('#board').value){n.className='notice';n.textContent='Choose one Board first.';return}if(!state.fileData){n.className='notice';n.textContent='Choose or design an image first.';return}if(!$('#title').value.trim()){n.className='notice';n.textContent='Enter a title first.';return}const summary='Publish this one Pin now?\n\nTitle: '+$('#title').value.trim()+'\nBoard: '+($('#board').selectedOptions[0]?.textContent||$('#board').value)+'\n\nOnly this user-selected Pin will be created.';if(!confirm(summary))return;$('#publish').disabled=true;n.className='notice';n.textContent='Publishing the selected Pin…';try{const d=await api('/api/pinterest?action=create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sandbox:false,board_id:$('#board').value,title:$('#title').value,description:$('#description').value,destination:$('#destination').value,alt_text:$('#altText').value,image_base64:state.fileData,content_type:state.fileType})});n.className='notice success';n.textContent='Pin published successfully. Pinterest Pin ID: '+d.pin.id;loadAnalytics()}catch(e){n.className='notice';n.textContent=e.message||'Pinterest could not publish this Pin.'}finally{$('#publish').disabled=false}};

$$('.mode-tab').forEach(b=>b.onclick=()=>{$$('.mode-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.mode-panel').forEach(x=>x.classList.add('hidden'));$('#mode-'+b.dataset.mode).classList.remove('hidden')});
$('#generateVariations').onclick=()=>{const title=$('#blogTitle').value.trim(),summary=$('#blogSummary').value.trim(),url=$('#blogUrl').value.trim();if(!title){alert('Add the article title first.');return}const clean=title.replace(/[.!?]+$/,'');const desc=summary||('Explore '+clean+' with practical ideas you can use and save for later.');const vars=[{title:clean,description:desc},{title:'A practical guide to '+clean.replace(/^how to /i,''),description:desc},{title:clean+' — ideas worth saving',description:desc}];$('#variationGrid').innerHTML=vars.map((v,i)=>'<button class="variation-card" data-variation="'+i+'"><strong>'+esc(v.title.slice(0,100))+'</strong><p>'+esc(v.description.slice(0,170))+'</p></button>').join('');$$('[data-variation]').forEach(b=>b.onclick=()=>{const v=vars[Number(b.dataset.variation)];$('#title').value=v.title.slice(0,100);$('#description').value=v.description.slice(0,800);$('#destination').value=url;updatePreview();window.scrollTo({top:document.querySelector('.publish-form').offsetTop-80,behavior:'smooth'})})};

function designerCtx(){return $('#designerCanvas').getContext('2d')}
function drawWrapped(ctx,text,x,y,maxWidth,lineHeight,maxLines=5){const words=String(text||'Your Pin headline').split(/\s+/);let line='',lines=[];for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=test}if(line&&lines.length<maxLines)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return lines.length}
function renderDesigner(){const c=$('#designerCanvas'),ctx=designerCtx(),style=$('#designerStyle').value,headline=$('#designerHeadline').value.trim()||'Your Pin headline',brand=$('#designerBrand').value.trim()||'yourdomain.com';ctx.clearRect(0,0,c.width,c.height);if(state.designerImage){const img=state.designerImage,scale=Math.max(c.width/img.width,c.height/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h)}else{const g=ctx.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,'#ece9ff');g.addColorStop(1,'#d8dce5');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height)}if(style==='editorial'){const g=ctx.createLinearGradient(0,c.height*.42,0,c.height);g.addColorStop(0,'rgba(12,12,16,0)');g.addColorStop(1,'rgba(12,12,16,.86)');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.font='700 82px Georgia';ctx.textAlign='left';drawWrapped(ctx,headline,72,1040,850,92,4);ctx.font='700 28px Arial';ctx.fillText(brand.toUpperCase(),74,1390)}else if(style==='clean'){ctx.fillStyle='rgba(255,255,255,.91)';ctx.fillRect(55,930,890,430);ctx.fillStyle='#17171d';ctx.font='700 72px Arial';ctx.textAlign='left';drawWrapped(ctx,headline,100,1035,800,82,4);ctx.font='700 27px Arial';ctx.fillStyle='#6255b8';ctx.fillText(brand.toUpperCase(),102,1305)}else{ctx.fillStyle='rgba(38,24,83,.78)';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.font='800 94px Arial';ctx.textAlign='center';drawWrapped(ctx,headline,500,590,820,108,5);ctx.font='700 30px Arial';ctx.fillText(brand.toUpperCase(),500,1325)}state.designerData=c.toDataURL('image/jpeg',.92)}
$('#designerImage').onchange=()=>{const f=$('#designerImage').files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)){alert('Use JPG, PNG or WebP.');return}const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{state.designerImage=img;renderDesigner()};img.src=String(r.result)};r.readAsDataURL(f)};$('#designerHeadline').oninput=renderDesigner;$('#designerBrand').oninput=renderDesigner;$('#designerStyle').onchange=renderDesigner;$('#renderDesign').onclick=renderDesigner;$('#useDesign').onclick=()=>{renderDesigner();const data=state.designerData,i=data.indexOf(',');state.fileData=data.slice(i+1);state.fileType='image/jpeg';$('#preview').style.backgroundImage='url("'+data+'")';$('#preview').innerHTML='';if(!$('#title').value.trim())$('#title').value=$('#designerHeadline').value.trim().slice(0,100);updatePreview();$('#publishNotice').className='notice success';$('#publishNotice').textContent='Designer image is ready. Review the Pin details before publishing.'};renderDesigner();

function currentDraft(){return{title:$('#title').value.trim(),description:$('#description').value.trim(),destination:$('#destination').value.trim(),alt_text:$('#altText').value.trim(),saved_at:new Date().toISOString()}}
function applyDraft(d){$('#title').value=d.title||'';$('#description').value=d.description||'';$('#destination').value=d.destination||'';$('#altText').value=d.alt_text||'';updatePreview();show('create');$('#publishNotice').className='notice';$('#publishNotice').textContent='Draft loaded. Select a Board and image, review everything, then publish if you choose.'}
$('#saveDraft').onclick=()=>{const w=workspace(),d=currentDraft();d.id=crypto.randomUUID?crypto.randomUUID():String(Date.now());d.label=d.title||'Untitled draft';w.drafts.unshift(d);saveWorkspace(w);renderPlanner();$('#publishNotice').className='notice success';$('#publishNotice').textContent='Draft saved locally in this browser. Images and Pinterest API data are not stored in the draft.'};
$('#saveToPlanner').onclick=()=>{const when=$('#planWhen').value,label=$('#planLabel').value.trim(),d=currentDraft();if(!d.title){alert('Add a Pin title in Create first.');return}if(!when){alert('Choose a planned date and time.');return}const w=workspace();d.id=crypto.randomUUID?crypto.randomUUID():String(Date.now());d.label=label||d.title;d.planned_for=when;w.drafts.unshift(d);saveWorkspace(w);$('#planLabel').value='';renderPlanner()};
function renderPlanner(){const w=workspace(),items=w.drafts||[];$('#plannerCount').textContent=String(items.length);$('#plannerList').innerHTML=items.map(d=>'<div class="planner-item"><div><strong>'+esc(d.label||d.title||'Untitled draft')+'</strong><small>'+esc(d.planned_for?formatDate(d.planned_for):'Draft · no planned time')+' · Board is selected only at publish time'+'</small></div><div class="planner-actions"><button class="mini" data-load-draft="'+esc(d.id)+'">Open</button><button class="mini danger" data-remove-draft="'+esc(d.id)+'">Remove</button></div></div>').join('')||'<div class="empty-state">No planned Pins yet.</div>';$$('[data-load-draft]').forEach(b=>b.onclick=()=>{const d=workspace().drafts.find(x=>x.id===b.dataset.loadDraft);if(d)applyDraft(d)});$$('[data-remove-draft]').forEach(b=>b.onclick=()=>{const w=workspace();w.drafts=w.drafts.filter(x=>x.id!==b.dataset.removeDraft);saveWorkspace(w);renderPlanner()})}
function clearLocal(){if(!confirm('Clear all locally saved drafts and planner items from this browser?'))return;localStorage.removeItem(STORAGE_KEY);renderPlanner()}
$('#clearPlanner').onclick=clearLocal;$('#clearWorkspace').onclick=clearLocal;

$('#disconnectPinterest').onclick=async()=>{if(!confirm('Disconnect Pinterest from this browser?'))return;try{await api('/api/pinterest?action=disconnect',{method:'POST'});location.href='/?disconnected=1'}catch(e){alert(e.message||'Could not disconnect')}};

async function init(){renderPlanner();await loadStatus();if(state.productionConnected){await Promise.all([loadAccount(),loadAnalytics()])}else{$('#accountLabel').textContent='Not connected'}const qs=new URLSearchParams(location.search);if(qs.get('oauth'))show(qs.get('oauth')==='sandbox-connected'?'settings':'dashboard')}
init();