const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const state={fileData:null,fileType:null,sandboxConnected:false,productionConnected:false};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function compact(v){const n=Number(v||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?Math.round(n/1e3)+'K':String(Math.round(n))}
async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));
function show(name){$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$$('.page').forEach(p=>p.classList.remove('active'));$('#page-'+name).classList.add('active');if(name==='analytics')loadAnalytics();if(name==='create')loadStatus();if(name==='demo')runChecks()}
async function loadStatus(){try{const s=await api('/api/pinterest?action=status');const connected=s.productionConnected||s.sandboxConnected;$('#connectionDot').classList.toggle('on',connected);$('#connectionText').textContent=s.productionConnected?'OAuth connected':s.sandboxConnected?'Sandbox connected':'Not connected';state.productionConnected=!!s.productionConnected;state.sandboxConnected=!!s.sandboxConnected;const n=$('#createNotice');if(s.productionConnected){n.className='notice success';n.textContent='Pinterest is connected. Production publishing is available.';const d=await api('/api/pinterest?action=boards');$('#board').innerHTML=(d.boards||[]).map(b=>'<option value="'+esc(b.id)+'">'+esc(b.name||b.id)+'</option>').join('')||'<option value="">No Boards returned</option>';$('#publish').disabled=!(d.boards||[]).length;const c=$('#productionConnect');if(c)c.textContent='Reconnect Pinterest'}else{n.className='notice';n.textContent='Connect Pinterest to load your Boards and publish.';$('#board').innerHTML='<option value="">Connect Pinterest first…</option>';$('#publish').disabled=true}}catch(e){const n=$('#createNotice');if(n){n.className='notice';n.textContent=e.message||'Could not load Pinterest connection.'}$('#publish').disabled=true}}
async function loadAccount(){try{const d=await api('/api/pinterest?action=account');const label=d.account?.username?'@'+d.account.username:'Connected';$('#accountLabel').textContent=label;$('#connectionText').textContent=label;$('#connectionDot').classList.add('on')}catch{$('#accountLabel').textContent='Access setup'}}
async function loadAnalytics(){const n=$('#analyticsNotice');n.className='notice';n.textContent='Loading authorized analytics…';try{const d=await api('/api/pinterest?action=analytics');const m=d.summary||{};$('#metricImpressions').textContent=compact(m.IMPRESSION);$('#metricSaves').textContent=compact(m.SAVE);$('#metricClicks').textContent=compact(m.PIN_CLICK);$('#metricOutbound').textContent=compact(m.OUTBOUND_CLICK);$('#topPins').innerHTML=(d.topPins||[]).map(p=>'<tr><td>'+esc(p.pin_id||'—')+'</td><td>'+compact(p.metrics?.IMPRESSION)+'</td><td>'+compact(p.metrics?.SAVE)+'</td><td>'+compact(p.metrics?.PIN_CLICK)+'</td><td>'+compact(p.metrics?.OUTBOUND_CLICK)+'</td></tr>').join('')||'<tr><td colspan="5">Pinterest returned no Top Pins for this date range.</td></tr>';n.className='notice success';n.textContent='Live organic analytics loaded for the authorized Pinterest account.';return true}catch{n.className='notice';n.textContent='Pinterest API access is not connected yet.';$('#topPins').innerHTML='<tr><td colspan="5">Analytics will load after access is approved and OAuth is connected.</td></tr>';return false}}
$('#refreshAnalytics').onclick=loadAnalytics;
const disconnectBtn=$('#disconnectPinterest');if(disconnectBtn)disconnectBtn.onclick=async()=>{if(!confirm('Disconnect Pinterest from this browser?'))return;try{await api('/api/pinterest?action=disconnect',{method:'POST'});location.href='/?disconnected=1'}catch(e){alert(e.message||'Could not disconnect')}};
$('#title').oninput=()=>$('#previewTitle').textContent=$('#title').value||'Your title';
$('#description').oninput=()=>$('#previewDescription').textContent=$('#description').value||'Your description will appear here.';
$('#imageFile').onchange=()=>{const f=$('#imageFile').files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)){alert('Use JPG, PNG or WebP.');return}if(f.size>3*1024*1024){alert('Use an image under 3 MB for this upload.');return}const r=new FileReader();r.onload=()=>{const data=String(r.result),i=data.indexOf(',');state.fileData=data.slice(i+1);state.fileType=f.type;$('#preview').style.backgroundImage='url("'+data+'")';$('#preview').textContent=''};r.readAsDataURL(f)};
$('#publish').onclick=async()=>{const n=$('#publishNotice');if(!state.productionConnected){n.className='notice';n.textContent='Connect Pinterest before publishing.';return}if(!$('#board').value){n.className='notice';n.textContent='Choose a Board first.';return}if(!state.fileData){n.className='notice';n.textContent='Choose an image first.';return}if(!$('#title').value.trim()){n.className='notice';n.textContent='Enter a title first.';return}if(!confirm('Publish this one user-selected Pin to the connected Pinterest account now?'))return;$('#publish').disabled=true;n.className='notice';n.textContent='Publishing the selected Pin…';try{const d=await api('/api/pinterest?action=create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sandbox:false,board_id:$('#board').value,title:$('#title').value,description:$('#description').value,destination:$('#destination').value,alt_text:$('#altText').value,image_base64:state.fileData,content_type:state.fileType})});n.className='notice success';n.textContent='Pin published successfully. Pinterest Pin ID: '+d.pin.id}catch(e){n.className='notice';n.textContent=e.message||'Pinterest could not publish this Pin.'}finally{$('#publish').disabled=false}};
async function runChecks(){let s={};try{s=await api('/api/pinterest?action=status')}catch{};$('#checkOAuth').className='check '+(s.productionConnected?'good':'');$('#checkOAuthText').textContent=s.productionConnected?'Connected via OAuth':'Awaiting connection';$('#checkSandbox').className='check '+(s.sandboxConnected?'good':'');$('#checkSandboxText').textContent=s.sandboxConnected?'Connected':'Awaiting connection';const analytics=await loadAnalytics();$('#checkAnalytics').className='check '+(analytics?'good':'');$('#checkAnalyticsText').textContent=analytics?'Authorized metrics working':'Awaiting connection'}
loadAccount();loadStatus();
const qs=new URLSearchParams(location.search);if(qs.get('oauth'))show(qs.get('oauth')==='sandbox-connected'?'create':'demo');
