const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const state={
  user:null,dbConfigured:false,productionConnected:false,sandboxConnected:false,boards:[],pins:[],analytics:null,schedule:[],
  ai:{textAI:false,imageAI:false,provider:'Smart fallback',textModels:[],imageModels:[],costs:{text:0,image:{low:0,medium:0,high:0}},credits:0},billing:null,article:null,wpPosts:[],sites:[],admin:null,analyticsMetric:'IMPRESSION',chartPoints:new Map(),
  fileData:null,fileType:null,fileName:null,fileBytes:null,remoteImage:null,imageSource:null,lastPack:null
};
const PAGE_META={dashboard:['Dashboard','Content operations at a glance'],create:['Create Pin','Manual + AI-assisted creative workflow'],blog:['Blog → Pin','Import, generate, review and schedule'],scheduler:['Scheduler','Approved future publishing'],library:['Pin Library','Full authorized account library'],analytics:['Analytics','Organic performance'],boards:['Boards','Organize content'],integrations:['Integrations','Connections and safeguards'],plans:['Plans','Subscriptions and queue capacity'],settings:['Settings','Account and authorization'],admin:['Owner Console','Private provider and customer controls']};
const fmt=new Intl.NumberFormat();
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function compact(v){const n=Number(v||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(n>=1e5?0:1)+'K':fmt.format(Math.round(n))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{};if(!r.ok){const e=new Error(d.error||('HTTP '+r.status));e.status=r.status;e.data=d;throw e}return d}
function post(url,body){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})})}
function show(name){if(name==='admin'&&state.user?.role!=='owner'){toast('Owner access required');name='dashboard'}$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$$('.page').forEach(p=>p.classList.remove('active'));$('#page-'+name)?.classList.add('active');const m=PAGE_META[name]||[name,''];$('#pageTitle').textContent=m[0];$('#pageSubtitle').textContent=m[1];$('.sidebar')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(name==='analytics')loadAnalytics();if(name==='library'&&!state.pins.length)loadAllPins();if(name==='scheduler')loadSchedule();if(name==='blog')loadWebsites();if(name==='integrations')loadIntegrations();if(name==='plans')loadBilling();if(name==='settings')refreshSettings();if(name==='boards')loadBoards(true);if(name==='admin')loadAdmin()}
$$('.nav,.jump').forEach(b=>b.onclick=()=>show(b.dataset.page));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#accountAction').onclick=()=>show('settings');

function updateOnboarding(){
  const panel=$('#onboardingPanel');if(!panel)return;
  const checks=[
    !!state.user,
    !!state.productionConnected,
    !!(state.sites&&state.sites.length),
    !!((state.schedule&&state.schedule.length)||(state.pins&&state.pins.length))
  ];
  ['Account','Pinterest','Website','FirstPin'].forEach((n,i)=>{const el=$('#onboard'+n);if(el)el.className='step-dot '+(checks[i]?'done':'')});
  const count=checks.filter(Boolean).length,status=$('#onboardingStatus');if(status){status.textContent=count+' / 4 complete';status.className='status-chip '+(count===4?'good':'')};
  panel.classList.toggle('complete',count===4);
}
async function loadUser(){try{const d=await api('/api/auth/user?action=me');state.dbConfigured=!!d.configured;state.user=d.user||null}catch{state.dbConfigured=false;state.user=null}
  $('#accountAction').textContent=state.user?state.user.email:'Sign in';
  $('#authForms').classList.toggle('hidden',!!state.user);$('#signedInPanel').classList.toggle('hidden',!state.user);
  $('#accountStatus').textContent=state.user?'Signed in':state.dbConfigured?'Signed out':'Database not connected';$('#accountStatus').className='status-chip '+(state.user?'good':state.dbConfigured?'':'warn');
  $$('.owner-only').forEach(el=>el.classList.toggle('hidden',state.user?.role!=='owner'));
  if(state.user){
    $('#signedInEmail').textContent=state.user.email;$('#signedInPlan').textContent=state.user.plan||'free';$('#signedInRole').textContent=state.user.role||'user';
    $('#verificationStatus').textContent=state.user.email_verified?'Email verified':'Email not verified';
    $('#verificationStatus').className='status-chip '+(state.user.email_verified?'good':'warn');
    $('#resendVerification').classList.toggle('hidden',!!state.user.email_verified);
    $('#emailIntegration').textContent=state.user.email_verified?'Verified':'Verification needed';$('#emailIntegration').className='status-chip '+(state.user.email_verified?'good':'warn');
  }else if($('#emailIntegration')){$('#emailIntegration').textContent='Sign in required';$('#emailIntegration').className='status-chip'}
  if($('#adminDbStatus')){$('#adminDbStatus').textContent=state.dbConfigured?'Connected':'Not connected';$('#adminDbStatus').className='status-chip '+(state.dbConfigured?'good':'warn')}
  updateOnboarding();return state.user}
let authMode='login';$$$('.auth-tab').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=authMode==='signup'?'Create account':'Sign in'});
$('#authSubmit').onclick=async()=>{const n=$('#authNotice');n.className='notice subtle';n.textContent='Working…';try{const d=await post('/api/auth/user?action='+authMode,{email:$('#authEmail').value,password:$('#authPassword').value});state.user=d.user;n.className='notice success';n.textContent=authMode==='signup'?(d.verification?.sent?'Account created. Check your email for the verification link.':'Account created. Email verification will become available when the owner configures email delivery.'):'Signed in.';await loadUser();if(authMode==='signup'){show('dashboard');updateOnboarding()}toast(authMode==='signup'?(d.verification?.sent?'Account created — verify your email next':'Account created — connect Pinterest next'):'Signed in')}catch(e){n.className='notice error';n.textContent=e.message}};
$('#resendVerification').onclick=async()=>{try{await post('/api/auth/user?action=resend',{});$('#authNotice').className='notice success';$('#authNotice').textContent='Verification email sent. Check your inbox.';toast('Verification email sent')}catch(e){$('#authNotice').className='notice error';$('#authNotice').textContent=e.message}};
$('#logout').onclick=async()=>{try{await post('/api/auth/user?action=logout',{});await loadUser();toast('Signed out')}catch(e){toast(e.message)}};
$('#deleteAccount').onclick=async()=>{if(!state.user){toast('Sign in first');return}if(!confirm('Delete this workspace and its stored scheduler data? This cannot be undone.'))return;try{await api('/api/auth/user?action=delete',{method:'DELETE'});await loadUser();toast('Workspace deleted')}catch(e){toast(e.message)}};

async function loadStatus(){try{const s=await api('/api/pinterest?action=status');state.productionConnected=!!s.productionConnected;state.sandboxConnected=!!s.sandboxConnected;$('#connectionDot').classList.toggle('on',state.productionConnected);$('#connectionText').textContent=state.productionConnected?'Connected':'Not connected';$('#pinterestIntegration').textContent=state.productionConnected?'Connected':'Not connected';$('#pinterestIntegration').className='status-chip '+(state.productionConnected?'good':'warn');$('#pinterestSetting').textContent=state.productionConnected?'Connected':'Not connected';$('#pinterestSetting').className='status-chip '+(state.productionConnected?'good':'warn');$('#sandboxIntegration').textContent=state.sandboxConnected?'Connected':'Optional';$('#sandboxIntegration').className='status-chip '+(state.sandboxConnected?'good':'');if(state.productionConnected)await loadBoards();else{$('#board').innerHTML='<option value="">Connect Pinterest first…</option>';$('#publish').disabled=true;$('#schedulePin').disabled=true}updateOnboarding()}catch(e){$('#connectionText').textContent='Unavailable'}}
async function loadAccount(){if(!state.productionConnected)return;try{const d=await api('/api/pinterest?action=account');if(d.account?.username){$('#connectionText').textContent='@'+d.account.username;$('#accountAction').textContent=state.user?state.user.email:'@'+d.account.username}}catch{}}
async function loadBoards(force=false){if(state.boards.length&&!force){renderBoards();return state.boards}if(!state.productionConnected)return[];try{const d=await api('/api/pinterest?action=boards');state.boards=d.boards||[];renderBoards();return state.boards}catch(e){$('#boardNotice').className='notice error';$('#boardNotice').textContent=e.message;return[]}}
function renderBoards(){const opts=state.boards.map(b=>'<option value="'+esc(b.id)+'">'+esc(b.name||b.id)+'</option>').join('');$('#board').innerHTML=opts||'<option value="">No Boards returned</option>';$('#publish').disabled=!state.boards.length;$('#schedulePin').disabled=!state.boards.length;$('#boardCount').textContent=String(state.boards.length);$('#boardList').innerHTML=state.boards.map(b=>'<div class="board-card"><strong>'+esc(b.name||'Untitled Board')+'</strong><p>'+esc(b.description||'No description')+'</p><small>'+esc(b.privacy||'')+(b.pin_count!=null?' · '+compact(b.pin_count)+' Pins':'')+'</small></div>').join('')||'<div class="empty-state">No Boards returned.</div>';$('#pinBoardFilter').innerHTML='<option value="">All Boards</option>'+state.boards.map(b=>'<option value="'+esc(b.id)+'">'+esc(b.name||b.id)+'</option>').join('')}
$('#refreshBoards').onclick=()=>loadBoards(true);
$('#generateBoardCopy').onclick=async()=>{const topic=$('#boardTopic').value.trim();if(!topic){toast('Enter a topic first');return}try{const d=await post('/api/ai?action=text',{keyword:topic,brand:$('#brand').value});const b=d.boards?.[0];if(b){$('#newBoardName').value=b.name.slice(0,100);$('#newBoardDescription').value=b.description.slice(0,500);$('#boardNotice').className='notice success';$('#boardNotice').textContent=(d.mode==='ai'?'AI':'Smart')+' Board draft generated from your topic. Review it before creating.'}}catch(e){toast(e.message)}};
$('#createBoard').onclick=async()=>{const name=$('#newBoardName').value.trim(),description=$('#newBoardDescription').value.trim(),n=$('#boardNotice');if(!name){n.className='notice error';n.textContent='Enter a Board name.';return}if(!confirm('Create this exact Board on the connected Pinterest account?'))return;try{await post('/api/pinterest?action=create-board',{name,description});n.className='notice success';n.textContent='Board created.';$('#newBoardName').value='';$('#newBoardDescription').value='';state.boards=[];await loadBoards(true)}catch(e){n.className='notice error';n.textContent=e.message}};

function pinImage(p){
  const preferred=[p?.media?.images?.originals?.url,p?.media?.images?.['1200x']?.url,p?.media?.images?.['600x']?.url,p?.media?.images?.['400x300']?.url,p?.media?.image?.url,p?.media_source?.url,p?.image?.url];
  for(const v of preferred)if(/^https?:\/\//i.test(String(v||'')))return v;
  const seen=new Set();
  function walk(v,path='',depth=0){
    if(v==null||depth>7)return'';
    if(typeof v==='string'&&/^https?:\/\//i.test(v)&&/(image|media|url|src|cover|thumbnail|original)/i.test(path))return v;
    if(typeof v!=='object'||seen.has(v))return'';seen.add(v);
    for(const [k,x] of Object.entries(v)){const found=walk(x,path+'.'+k,depth+1);if(found)return found}
    return'';
  }
  return walk(p);
}
function pinMetrics(p){const pm=p?.pin_metrics||{};return pm['90d']||pm['30d']||pm.lifetime_metrics||pm.summary_metrics||pm.all_time||pm||{}}
function metric(m,key){return Number(m?.[key]??m?.[key.toLowerCase()]??0)}
function boardName(id){return state.boards.find(b=>String(b.id)===String(id))?.name||'Pinterest Board'}
async function loadAllPins(){if(!state.productionConnected){$('#libraryNotice').textContent='Connect Pinterest to load your library.';return}state.pins=[];let bookmark='',page=0;$('#libraryNotice').className='notice';$('#libraryNotice').textContent='Loading your authorized Pin library…';try{do{const d=await api('/api/pinterest?action=pins'+(bookmark?'&bookmark='+encodeURIComponent(bookmark):''));state.pins.push(...(d.pins||[]));bookmark=d.bookmark||'';page++;$('#pinLoadProgress').textContent=fmt.format(state.pins.length)+' loaded';renderPinLibrary();renderDashboardPins();if(page>1000)throw new Error('Stopped after 250,000 Pins for browser safety.')}while(bookmark);$('#libraryNotice').className='notice success';$('#libraryNotice').textContent='Loaded '+fmt.format(state.pins.length)+' Pins from the authorized Pinterest account using API pagination.';$('#heroPins').textContent=fmt.format(state.pins.length);updateOnboarding();renderTopPins()}catch(e){$('#libraryNotice').className='notice error';$('#libraryNotice').textContent=e.message}}
function renderPinLibrary(){const q=$('#pinSearch').value.trim().toLowerCase(),board=$('#pinBoardFilter').value,sort=$('#pinSort').value;let items=state.pins.filter(p=>(!board||String(p.board_id)===board)&&(!q||String(p.title||'').toLowerCase().includes(q)||String(p.description||'').toLowerCase().includes(q)));items=items.slice();if(sort!=='newest')items.sort((a,b)=>{const ma=pinMetrics(a),mb=pinMetrics(b),k=sort==='impressions'?'IMPRESSION':sort==='saves'?'SAVE':'OUTBOUND_CLICK';return metric(mb,k)-metric(ma,k)});$('#pinGrid').innerHTML=items.map(p=>{const m=pinMetrics(p),img=pinImage(p);return '<article class="pin-card"><div class="pin-image" '+(img?'style="background-image:url(&quot;'+esc(img)+'&quot;)"':'')+'><span class="board-pill">'+esc(boardName(p.board_id))+'</span></div><div class="pin-copy"><h3>'+esc(p.title||'Untitled Pin')+'</h3><div class="pin-stats"><div class="pin-stat"><small>Impressions</small><strong>'+compact(metric(m,'IMPRESSION'))+'</strong></div><div class="pin-stat"><small>Saves</small><strong>'+compact(metric(m,'SAVE'))+'</strong></div><div class="pin-stat"><small>Pin clicks</small><strong>'+compact(metric(m,'PIN_CLICK'))+'</strong></div><div class="pin-stat"><small>Outbound</small><strong>'+compact(metric(m,'OUTBOUND_CLICK'))+'</strong></div></div><div class="pin-links"><a href="https://www.pinterest.com/pin/'+esc(p.id)+'/" target="_blank" rel="noopener">Open on Pinterest</a>'+(p.link?'<a href="'+esc(p.link)+'" target="_blank" rel="noopener">Destination</a>':'')+'</div></div></article>'}).join('')||'<div class="empty-state">No Pins match this filter.</div>'}
function renderDashboardPins(){const items=state.pins.slice(0,6);$('#dashboardPins').innerHTML=items.map(p=>{const m=pinMetrics(p),img=pinImage(p);return '<div class="mini-pin-card"><div class="image" '+(img?'style="background-image:url(&quot;'+esc(img)+'&quot;)"':'')+'></div><div class="copy"><strong>'+esc(p.title||'Untitled Pin')+'</strong><small>'+compact(metric(m,'IMPRESSION'))+' impressions</small></div></div>'}).join('')||'<div class="empty-state">No Pins loaded.</div>';if(items[0]){const img=pinImage(items[0]);$('#heroPinImage').style.backgroundImage=img?'url("'+img.replace(/"/g,'%22')+'")':'';$('#heroPinTitle').textContent=items[0].title||'Visual analytics'}}
$('#reloadPins').onclick=loadAllPins;$('#pinSearch').oninput=renderPinLibrary;$('#pinBoardFilter').onchange=renderPinLibrary;$('#pinSort').onchange=renderPinLibrary;

const METRIC_LABELS={IMPRESSION:'Impressions',ENGAGEMENT:'Engagements',SAVE:'Saves',PIN_CLICK:'Pin clicks',OUTBOUND_CLICK:'Outbound clicks',ENGAGEMENT_RATE:'Engagement rate',SAVE_RATE:'Save rate',PIN_CLICK_RATE:'Pin click rate',OUTBOUND_CLICK_RATE:'Outbound click rate',TOTAL_AUDIENCE:'Total audience',ENGAGED_AUDIENCE:'Engaged audience',MONTHLY_TOTAL_AUDIENCE:'Monthly total audience',MONTHLY_ENGAGED_AUDIENCE:'Monthly engaged audience',MONTHLY_VIEWS:'Monthly views'};
function metricValueFromDay(x,key){return Number(x?.metrics?.[key]??x?.[key]??0)}
function normalizeSeries(series,key='IMPRESSION'){return(series||[]).map(x=>({date:x.date||x.DATE||'',value:metricValueFromDay(x,key)})).filter(x=>x.date)}
function formatMetricValue(v,key){const n=Number(v||0);if(String(key).endsWith('_RATE')){const pct=Math.abs(n)<=1?n*100:n;return pct.toFixed(2)+'%'}return compact(n)}
function drawLine(canvas,series,empty,key='IMPRESSION',interactive=false){
  const pts=normalizeSeries(series,key);if(!canvas)return;
  if(!pts.length){empty?.classList.remove('hidden');const cc=canvas.getContext('2d');cc.clearRect(0,0,canvas.width,canvas.height);canvas._chartPoints=[];return}
  empty?.classList.add('hidden');const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(300,Math.round(rect.width*dpr));canvas.height=Math.max(180,Math.round(rect.height*dpr));
  const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height,p={l:22,r:14,t:18,b:28},max=Math.max(...pts.map(x=>x.value),1),min=Math.min(...pts.map(x=>x.value),0),range=max-min||1;ctx.clearRect(0,0,w,h);
  ctx.strokeStyle='#ececf2';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=p.t+(h-p.t-p.b)*i/3;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke()}
  const xy=pts.map((d,i)=>({x:p.l+(w-p.l-p.r)*(pts.length===1?.5:i/(pts.length-1)),y:h-p.b-(h-p.t-p.b)*(d.value-min)/range,date:d.date,value:d.value}));
  const g=ctx.createLinearGradient(0,p.t,0,h-p.b);g.addColorStop(0,'rgba(107,76,230,.24)');g.addColorStop(1,'rgba(107,76,230,0)');
  ctx.beginPath();ctx.moveTo(xy[0].x,h-p.b);xy.forEach(q=>ctx.lineTo(q.x,q.y));ctx.lineTo(xy[xy.length-1].x,h-p.b);ctx.closePath();ctx.fillStyle=g;ctx.fill();
  ctx.beginPath();xy.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.strokeStyle='#6b4ce6';ctx.lineWidth=2.4;ctx.stroke();
  ctx.fillStyle='#6b4ce6';xy.forEach(q=>{ctx.beginPath();ctx.arc(q.x,q.y,2.3,0,Math.PI*2);ctx.fill()});
  ctx.font='8px system-ui';ctx.fillStyle='#979ba7';ctx.textAlign='center';[0,Math.floor((pts.length-1)/2),pts.length-1].forEach(i=>ctx.fillText(String(pts[i].date).slice(5),xy[i].x,h-8));
  canvas._chartPoints=xy;canvas._metricKey=key;
  if(interactive&&!canvas._hoverBound){
    canvas._hoverBound=true;
    canvas.addEventListener('mousemove',e=>{const points=canvas._chartPoints||[];if(!points.length)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left;let near=points[0];for(const pnt of points)if(Math.abs(pnt.x-x)<Math.abs(near.x-x))near=pnt;const tip=$('#analyticsTooltip');if(!tip)return;tip.innerHTML='<strong>'+esc(METRIC_LABELS[canvas._metricKey]||canvas._metricKey)+'</strong><span>'+formatMetricValue(near.value,canvas._metricKey)+'</span><small>'+esc(new Date(near.date+'T00:00:00').toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'}))+'</small>';tip.style.left=Math.min(r.width-150,Math.max(8,near.x+10))+'px';tip.style.top=Math.max(8,near.y-64)+'px';tip.classList.remove('hidden')});
    canvas.addEventListener('mouseleave',()=>$('#analyticsTooltip')?.classList.add('hidden'));
  }
}
async function loadAnalytics(force=false){const days=$('#analyticsRange')?.value||30;if(state.analytics&&!force&&String(state.analytics.days)===String(days)){renderAnalytics();return}if(!state.productionConnected)return;$('#analyticsNotice').className='notice';$('#analyticsNotice').textContent='Loading live organic analytics…';try{state.analytics=await api('/api/pinterest?action=analytics&days='+days);renderAnalytics();$('#analyticsNotice').className='notice success';$('#analyticsNotice').textContent='Live authorized organic analytics loaded.'}catch(e){$('#analyticsNotice').className='notice error';$('#analyticsNotice').textContent=e.message}}
function renderAnalytics(){
  const d=state.analytics||{},m=d.summary||{};
  [['metricImpressions','IMPRESSION'],['dashImpressions','IMPRESSION'],['metricEngagements','ENGAGEMENT'],['metricSaves','SAVE'],['dashSaves','SAVE'],['metricClicks','PIN_CLICK'],['metricOutbound','OUTBOUND_CLICK'],['dashOutbound','OUTBOUND_CLICK']].forEach(([id,k])=>{const el=$('#'+id);if(el)el.textContent=formatMetricValue(metric(m,k),k)});
  const key=state.analyticsMetric||'IMPRESSION';$('#analyticsChartTitle').textContent=(METRIC_LABELS[key]||key)+' over time';
  drawLine($('#analyticsChart'),d.series,$('#analyticsChartEmpty'),key,true);drawLine($('#dashboardChart'),d.series,$('#dashboardChartEmpty'),'IMPRESSION',false);renderTopPins()
}
function renderTopPins(){const tops=state.analytics?.topPins||[];if(!tops.length){$('#topPinCards').innerHTML='<div class="empty-state">Pinterest returned no Top Pins for this range.</div>';return}$('#topPinCards').innerHTML=tops.map((t,i)=>{const p=state.pins.find(x=>String(x.id)===String(t.pin_id)),img=p?pinImage(p):'',m=t.metrics||{};return '<article class="performance-card"><div class="performance-image '+(img?'':'missing')+'" '+(img?'style="background-image:url(&quot;'+esc(img)+'&quot;)"':'')+'>'+(img?'':'<span>Image unavailable in this API response</span>')+'</div><div class="performance-copy"><span class="kicker">#'+(i+1)+'</span><strong>'+esc(p?.title||('Pin '+t.pin_id))+'</strong><small>'+compact(metric(m,'IMPRESSION'))+' impressions · '+compact(metric(m,'SAVE'))+' saves · '+compact(metric(m,'PIN_CLICK'))+' Pin clicks · '+compact(metric(m,'OUTBOUND_CLICK'))+' outbound</small></div></article>'}).join('')}
$$('.metric-toggle[data-metric]').forEach(b=>b.onclick=()=>{state.analyticsMetric=b.dataset.metric;$$('.metric-toggle').forEach(x=>x.classList.toggle('active',x===b));renderAnalytics()});
$('#refreshAnalytics').onclick=()=>loadAnalytics(true);$('#analyticsRange').onchange=()=>loadAnalytics(true);$('#refreshDashboard').onclick=async()=>{state.analytics=null;await Promise.all([loadAnalytics(true),loadSchedule()])};

async function loadAI(){try{
  state.ai=await api('/api/ai');
  $('#aiTextStatus').textContent=state.ai.textAI?'AI ready':'Smart fallback';$('#aiTextStatus').className='status-chip '+(state.ai.textAI?'good':'warn');
  $('#aiIntegration').textContent=state.ai.textAI?('Ready · '+state.ai.credits+' credits'):'Smart fallback';$('#aiIntegration').className='status-chip '+(state.ai.textAI?'good':'warn');
  $('#aiCreditBalance').textContent=String(state.ai.credits||0);
  $('#aiTextModel').innerHTML=(state.ai.textModels||[]).map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')||'<option value="">No AI model configured</option>';
  $('#aiImageModel').innerHTML=(state.ai.imageModels||[]).map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')||'<option value="">No image model configured</option>';
  $('#aiTextCost').textContent=(state.ai.costs?.text||0)+' credit'+((state.ai.costs?.text||0)===1?'':'s');
  updateImageCost();
  $('#aiImageNotice').textContent=state.ai.imageAI?'AI image generation is available. Generated-image provenance is not intentionally removed or hidden.':'AI images are not configured yet. Upload and template tools still work.';
}catch(e){}}
function updateAICredits(n){if(n==null)return;state.ai.credits=Number(n);$('#aiCreditBalance').textContent=String(state.ai.credits);if(state.user)state.user.ai_credits=state.ai.credits}
function updateImageCost(){const q=$('#aiImageQuality')?.value||'medium',n=state.ai.costs?.image?.[q]??0;if($('#aiImageCost'))$('#aiImageCost').textContent=n+' credits'}
$('#aiImageQuality').onchange=updateImageCost;
async function generatePack(input){const payload={...input,model:$('#aiTextModel')?.value||'',instructions:$('#aiInstructions')?.value||''},d=await post('/api/ai?action=text',payload);state.lastPack=d;updateAICredits(d.credits);return d}
function renderVariants(container,d,onUse){container.innerHTML=(d.variants||[]).map((v,i)=>'<button class="variant-card" data-var="'+i+'"><strong>'+esc(v.title)+'</strong><p>'+esc(v.description)+'</p><span class="status-chip">'+(d.mode==='ai'?(esc(d.model||'AI')):'Smart')+' option '+(i+1)+'</span></button>').join('');container.querySelectorAll('[data-var]').forEach(b=>b.onclick=()=>onUse(d.variants[Number(b.dataset.var)]))}
function useVariant(v){$('#title').value=v.title.slice(0,100);$('#description').value=v.description.slice(0,800);$('#altText').value=v.alt_text.slice(0,500);updatePreview();$('#titleCount').textContent=$('#title').value.length+' / 100'}
$('#generateCopy').onclick=async()=>{const keyword=$('#keyword').value.trim();if(!keyword){toast('Enter a keyword or topic');return}try{const d=await generatePack({keyword,brand:$('#brand').value});renderVariants($('#copyVariants'),d,useVariant);if(d.image_prompt)$('#imagePrompt').value=d.image_prompt;toast(d.mode==='ai'?('Generated with '+(d.model||'AI')):'Smart options generated')}catch(e){toast(e.message)}};

function updatePreview(){const title=$('#title').value||'Your Pin title',desc=$('#description').value||'Your description will appear here.';$('#previewTitle').textContent=title;$('#previewDescription').textContent=desc;$('#titleCount').textContent=$('#title').value.length+' / 100';try{$('#previewDomain').textContent=new URL($('#destination').value).hostname}catch{$('#previewDomain').textContent='your-site.com'}}
$('#title').oninput=updatePreview;$('#description').oninput=updatePreview;$('#destination').oninput=updatePreview;
$$('.visual-tab').forEach(b=>b.onclick=()=>{$$('.visual-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.visual-panel').forEach(x=>x.classList.add('hidden'));$('#visual-'+b.dataset.visual).classList.remove('hidden')});
function setImageData(b64,type,name,source='upload'){state.fileData=b64;state.fileType=type;state.fileName=name||'pin-image.jpg';state.remoteImage=null;state.imageSource=source;$('#preview').style.backgroundImage='url("data:'+type+';base64,'+b64+'")';$('#preview').innerHTML=''}
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(r.result);r.readAsArrayBuffer(file)})}
function arrToB64(arr){let s='',u=new Uint8Array(arr),chunk=0x8000;for(let i=0;i<u.length;i+=chunk)s+=String.fromCharCode(...u.subarray(i,i+chunk));return btoa(s)}
$('#imageFile').onchange=async()=>{const f=$('#imageFile').files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)){toast('Use JPG, PNG or WebP');return}if(f.size>3*1024*1024){toast('Use an image under 3 MB for direct publishing');return}const buf=await readFile(f);state.fileBytes=buf;setImageData(arrToB64(buf),f.type,f.name,'upload')};
function stripJpegPrivate(buf){const u=new Uint8Array(buf);if(u[0]!==0xff||u[1]!==0xd8)throw new Error('Not a valid JPEG.');const parts=[u.slice(0,2)];let p=2;while(p<u.length){if(u[p]!==0xff){parts.push(u.slice(p));break}const marker=u[p+1];if(marker===0xd9||marker===0xda){parts.push(u.slice(p));break}if(p+4>u.length)break;const len=(u[p+2]<<8)|u[p+3],end=p+2+len;if(end>u.length)break;const seg=u.slice(p,end),isExif=marker===0xe1&&u[p+4]===0x45&&u[p+5]===0x78&&u[p+6]===0x69&&u[p+7]===0x66;const isComment=marker===0xfe;if(!isExif&&!isComment)parts.push(seg);p=end}const size=parts.reduce((n,x)=>n+x.length,0),out=new Uint8Array(size);let o=0;for(const x of parts){out.set(x,o);o+=x.length}return out.buffer}
function stripPngPrivate(buf){const u=new Uint8Array(buf),sig=[137,80,78,71,13,10,26,10];if(!sig.every((v,i)=>u[i]===v))throw new Error('Not a valid PNG.');const parts=[u.slice(0,8)];let p=8;while(p+12<=u.length){const len=(u[p]<<24)|(u[p+1]<<16)|(u[p+2]<<8)|u[p+3],end=p+12+len,type=String.fromCharCode(u[p+4],u[p+5],u[p+6],u[p+7]);if(end>u.length)break;if(type!=='eXIf')parts.push(u.slice(p,end));p=end;if(type==='IEND')break}const size=parts.reduce((n,x)=>n+x.length,0),out=new Uint8Array(size);let o=0;for(const x of parts){out.set(x,o);o+=x.length}return out.buffer}
$('#cleanMetadata').onclick=()=>{if(state.imageSource==='ai'){toast('AI-generated provenance is intentionally not stripped');return}if(!state.fileBytes){toast('Upload a JPEG or PNG first');return}try{let out;if(state.fileType==='image/jpeg')out=stripJpegPrivate(state.fileBytes);else if(state.fileType==='image/png')out=stripPngPrivate(state.fileBytes);else{toast('Privacy cleaning currently supports JPEG and PNG');return}state.fileBytes=out;setImageData(arrToB64(out),state.fileType,(state.fileName||'image').replace(/(\.\w+)?$/,'-privacy-clean$1'),'cleaned');toast('Private EXIF/GPS metadata removed without recompressing pixels')}catch(e){toast(e.message)}};

function imageElement(){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;if(state.fileData)img.src='data:'+state.fileType+';base64,'+state.fileData;else if(state.remoteImage){img.crossOrigin='anonymous';img.src=state.remoteImage}else resolve(null)})}
function wrapped(ctx,text,x,y,maxWidth,lineHeight,maxLines,center=false){const words=String(text||'').split(/\s+/);let line='',lines=[];for(const word of words){const t=line?line+' '+word:word;if(ctx.measureText(t).width>maxWidth&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=t}if(line&&lines.length<maxLines)lines.push(line);ctx.textAlign=center?'center':'left';lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return lines.length}
async function makeTemplate(){const c=$('#templateCanvas'),ctx=c.getContext('2d'),style=$('#templateStyle').value,headline=$('#title').value.trim()||$('#keyword').value.trim()||state.article?.title||'Your Pin headline',footer=$('#templateFooter').value.trim()||$('#brand').value.trim()||'yourdomain.com';ctx.clearRect(0,0,c.width,c.height);let img=null;try{img=await imageElement()}catch{}if(img){const scale=Math.max(c.width/img.width,c.height/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h)}else{const g=ctx.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,'#e7e0ff');g.addColorStop(1,'#d6e2ef');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height)}if(style==='editorial'){const g=ctx.createLinearGradient(0,560,0,1500);g.addColorStop(0,'rgba(15,15,20,0)');g.addColorStop(1,'rgba(15,15,20,.88)');ctx.fillStyle=g;ctx.fillRect(0,0,1000,1500);ctx.fillStyle='#fff';ctx.font='700 82px Georgia';wrapped(ctx,headline,70,1050,850,94,4);ctx.font='700 27px Arial';ctx.fillText(footer.toUpperCase(),72,1400)}else if(style==='clean'){ctx.fillStyle='rgba(255,255,255,.93)';ctx.fillRect(55,905,890,445);ctx.fillStyle='#171820';ctx.font='700 72px Arial';wrapped(ctx,headline,95,1010,800,82,4);ctx.font='700 26px Arial';ctx.fillStyle='#6546ce';ctx.fillText(footer.toUpperCase(),97,1300)}else if(style==='bold'){ctx.fillStyle='rgba(42,27,91,.77)';ctx.fillRect(0,0,1000,1500);ctx.fillStyle='#fff';ctx.font='800 92px Arial';wrapped(ctx,headline,500,590,820,108,5,true);ctx.font='700 28px Arial';ctx.fillText(footer.toUpperCase(),500,1320)}else{ctx.fillStyle='rgba(255,255,255,.86)';ctx.fillRect(90,100,820,1300);ctx.fillStyle='#1d1d24';ctx.font='700 74px Georgia';wrapped(ctx,headline,500,520,710,88,5,true);ctx.font='700 25px Arial';ctx.fillStyle='#5b5f69';ctx.fillText(footer.toUpperCase(),500,1240)}const data=c.toDataURL('image/jpeg',.92),i=data.indexOf(',');setImageData(data.slice(i+1),'image/jpeg',(headline.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'pin')+'.jpg','template');toast('2:3 template generated')}
$('#makeTemplate').onclick=makeTemplate;
$('#generateImage').onclick=async()=>{const p=$('#imagePrompt').value.trim();if(!p){toast('Enter an image prompt');return}$('#aiImageNotice').className='notice subtle';$('#aiImageNotice').textContent='Generating image…';try{const d=await post('/api/ai?action=image',{prompt:p,model:$('#aiImageModel').value,quality:$('#aiImageQuality').value});setImageData(d.image.b64,d.image.content_type,'ai-generated-pin.jpg','ai');state.fileBytes=null;updateAICredits(d.credits);$('#aiImageNotice').className='notice success';$('#aiImageNotice').textContent='AI image generated with '+d.image.model+' · '+d.image.quality+'. Provenance/content credentials are not intentionally stripped.'}catch(e){$('#aiImageNotice').className='notice error';$('#aiImageNotice').textContent=e.message}};

function currentPayload(){const b=state.boards.find(x=>String(x.id)===$('#board').value);return{board_id:$('#board').value,board_name:b?.name||'',title:$('#title').value.trim(),description:$('#description').value.trim(),destination:$('#destination').value.trim(),alt_text:$('#altText').value.trim(),image_base64:state.fileData,image_data:state.fileData,image_url:state.remoteImage,content_type:state.fileType||'image/jpeg',file_name:state.fileName||'pin-image.jpg'}}
function validatePin(p){if(!state.productionConnected)return'Connect Pinterest first.';if(!p.board_id)return'Choose a Board.';if(!p.title)return'Enter a title.';if(!p.image_base64&&!p.image_url)return'Choose or generate an image.';return''}
$('#publish').onclick=async()=>{const p=currentPayload(),err=validatePin(p),n=$('#publishNotice');if(err){n.className='notice error';n.textContent=err;return}if(!confirm('Publish this exact user-reviewed Pin now?'))return;n.className='notice';n.textContent='Publishing…';$('#publish').disabled=true;try{const d=await post('/api/pinterest?action=create',{sandbox:false,board_id:p.board_id,title:p.title,description:p.description,destination:p.destination,alt_text:p.alt_text,image_base64:p.image_base64,image_url:p.image_url,content_type:p.content_type});n.className='notice success';n.textContent='Published successfully. Pinterest Pin ID: '+d.pin.id;state.pins=[];toast('Pin published')}catch(e){n.className='notice error';n.textContent=e.message}finally{$('#publish').disabled=!state.boards.length}};
function setDefaultSchedule(){const d=new Date(Date.now()+60*60000);d.setSeconds(0,0);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#scheduleAt').value=local}
function makeThumb(){return new Promise(async resolve=>{if(!state.fileData){resolve(null);return}try{const img=await imageElement(),c=document.createElement('canvas');c.width=240;c.height=360;const x=c.getContext('2d'),scale=Math.max(c.width/img.width,c.height/img.height),w=img.width*scale,h=img.height*scale;x.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);resolve(c.toDataURL('image/jpeg',.62).split(',')[1])}catch{resolve(null)}})}
$('#schedulePin').onclick=async()=>{const p=currentPayload(),err=validatePin(p),n=$('#publishNotice');if(err){n.className='notice error';n.textContent=err;return}if(!state.user){show('settings');toast('Create an account or sign in to schedule');return}if(!$('#approveSchedule').checked){n.className='notice error';n.textContent='Check the approval box after reviewing this exact Pin.';return}const when=new Date($('#scheduleAt').value);if(Number.isNaN(when.getTime())){n.className='notice error';n.textContent='Choose a future date and time.';return}if(!confirm('Schedule this exact reviewed Pin for '+when.toLocaleString()+'?'))return;n.className='notice';n.textContent='Adding to queue…';try{p.image_thumb=await makeThumb();await post('/api/schedule',{...p,scheduled_at:when.toISOString(),approved:true});n.className='notice success';n.textContent='Scheduled. The server enforces at least 30 minutes between queued Pins.';$('#approveSchedule').checked=false;await loadSchedule();toast('Pin scheduled')}catch(e){n.className='notice error';n.textContent=e.message}};

async function importRemoteImage(url){if(!url)return false;try{const d=await api('/api/blog?action=image&url='+encodeURIComponent(url));state.fileData=d.data;state.fileType=d.content_type;state.fileName='article-pin-image.'+(d.content_type.includes('png')?'png':d.content_type.includes('webp')?'webp':'jpg');state.fileBytes=null;state.remoteImage=url;state.imageSource='article';$('#preview').style.backgroundImage='url("'+url.replace(/"/g,'%22')+'")';$('#preview').innerHTML='';return true}catch{return false}}
function setArticle(a){state.article=a;$('#selectedArticleTitle').textContent=a.title||'Untitled article';$('#selectedArticleSummary').textContent=a.description||a.excerpt||'No summary found.';$('#selectedArticleUrl').textContent=a.url||'';$('#selectedArticleImage').style.backgroundImage=a.image?'url("'+a.image.replace(/"/g,'%22')+'")':''}
$('#loadWp').onclick=async()=>{const n=$('#wpNotice'),site=$('#wpSite').value.trim();if(!site){n.className='notice error';n.textContent='Enter a WordPress site URL.';return}n.className='notice';n.textContent='Loading published posts…';try{const d=await api('/api/blog?action=wordpress&site='+encodeURIComponent(site));state.wpPosts=d.posts||[];$('#wpCount').textContent=state.wpPosts.length+' posts';$('#wpPosts').innerHTML=state.wpPosts.map((p,i)=>'<button class="post-card" data-post="'+i+'"><div class="post-image" '+(p.image?'style="background-image:url(&quot;'+esc(p.image)+'&quot;)"':'')+'></div><div class="post-copy"><strong>'+esc(p.title)+'</strong><small>'+esc(p.date?new Date(p.date).toLocaleDateString():'Published post')+'</small></div></button>').join('')||'<div class="empty-state">No published posts returned.</div>';$$('[data-post]').forEach(b=>b.onclick=()=>setArticle({...state.wpPosts[Number(b.dataset.post)],description:state.wpPosts[Number(b.dataset.post)].excerpt}));n.className='notice success';n.textContent='Loaded '+state.wpPosts.length+' published posts from your WordPress REST feed.'}catch(e){n.className='notice error';n.textContent=e.message}};
$('#importArticle').onclick=async()=>{const n=$('#articleNotice'),url=$('#articleUrl').value.trim();if(!url){n.className='notice error';n.textContent='Paste an article URL.';return}n.className='notice';n.textContent='Importing public article metadata…';try{const d=await api('/api/blog?url='+encodeURIComponent(url));setArticle(d.article);n.className='notice success';n.textContent='Article imported. Review it before generating.'}catch(e){n.className='notice error';n.textContent=e.message}};
$('#blogGenerate').onclick=async()=>{const n=$('#blogGenerateNotice');if(!state.article){n.className='notice error';n.textContent='Select or import an article first.';return}n.className='notice';n.textContent='Generating options from your selected article…';try{const d=await generatePack({article_title:state.article.title,article_summary:state.article.description||state.article.excerpt,article_url:state.article.url,brand:$('#brand').value,tone:$('#blogTone').value,audience:$('#blogAudience').value});renderVariants($('#blogVariants'),d,v=>{useVariant(v);$('#destination').value=state.article.url||'';state.remoteImage=state.article.image||null;state.fileData=null;state.fileType='image/jpeg';state.imageSource='article';if(state.remoteImage){$('#preview').style.backgroundImage='url("'+state.remoteImage.replace(/"/g,'%22')+'")';$('#preview').innerHTML=''}updatePreview();show('create')});if(d.image_prompt)$('#imagePrompt').value=d.image_prompt;n.className='notice success';n.textContent='Options created. Choose one, then review image, Board and schedule.'}catch(e){n.className='notice error';n.textContent=e.message}};
$('#useBlogTemplate').onclick=async()=>{if(!state.article){toast('Select an article first');return}$('#title').value=state.article.title.slice(0,100);$('#description').value=(state.article.description||state.article.excerpt||'').slice(0,800);$('#destination').value=state.article.url||'';if(state.article.image)await importRemoteImage(state.article.image);updatePreview();await makeTemplate();show('create')};
$('#useBlogAiImage').onclick=async()=>{if(!state.article){toast('Select an article first');return}try{const d=state.lastPack||await generatePack({article_title:state.article.title,article_summary:state.article.description||state.article.excerpt,article_url:state.article.url});$('#imagePrompt').value=d.image_prompt||('Vertical editorial image about '+state.article.title);show('create');$$('.visual-tab').forEach(x=>x.classList.toggle('active',x.dataset.visual==='ai'));$$('.visual-panel').forEach(x=>x.classList.add('hidden'));$('#visual-ai').classList.remove('hidden');toast('AI image prompt prepared. Review it before generating.')}catch(e){toast(e.message)}};

async function loadSchedule(){if(!$('#timezoneLabel'))return;$('#timezoneLabel').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone||'Local';try{const d=await api('/api/schedule');state.schedule=d.items||[];const active=state.schedule.filter(x=>x.status==='scheduled');$('#queueCount').textContent=$('#dashQueue').textContent=String(active.length);updateOnboarding();$('#queueLimit').textContent=active.length+' / '+d.limit;$('#schedulerNotice').className='notice success';$('#schedulerNotice').textContent='Persistent queue ready. Every scheduled item was explicitly approved. Background execution still needs a recurring worker trigger when the browser is closed.';renderSchedule();renderDashboardQueue(active);return true}catch(e){state.schedule=[];$('#queueCount').textContent=$('#dashQueue').textContent='0';$('#queueLimit').textContent='—';$('#schedulerNotice').className='notice';$('#schedulerNotice').textContent=e.status===401?'Create an account or sign in to use the persistent scheduler.':e.message;$('#scheduleList').innerHTML='<div class="empty-state">'+esc($('#schedulerNotice').textContent)+'</div>';renderDashboardQueue([]);return false}}
function queueImage(x){return x.image_thumb?'data:image/jpeg;base64,'+x.image_thumb:x.image_url||''}
function renderDashboardQueue(items){const upcoming=items.slice().sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at)).slice(0,4);$('#dashboardQueue').innerHTML=upcoming.map(x=>{const img=queueImage(x),d=new Date(x.scheduled_at);return '<div class="queue-item"><div class="queue-thumb" '+(img?'style="background-image:url(&quot;'+esc(img)+'&quot;)"':'')+'></div><div><strong>'+esc(x.title)+'</strong><small>'+esc(x.board_name||'Pinterest Board')+'</small></div><div class="queue-time">'+d.toLocaleDateString([],{month:'short',day:'numeric'})+'<br>'+d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+'</div></div>'}).join('')||'<div class="empty-state">Nothing scheduled yet.</div>';if(upcoming[0])$('#heroNext').textContent=new Date(upcoming[0].scheduled_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});else $('#heroNext').textContent='—'}
function renderSchedule(){const items=state.schedule.slice().sort((a,b)=>new Date(b.scheduled_at)-new Date(a.scheduled_at));$('#scheduleList').innerHTML=items.map(x=>{const d=new Date(x.scheduled_at),img=queueImage(x);return '<div class="timeline-item"><div class="timeline-time">'+d.toLocaleDateString([],{month:'short',day:'numeric'})+'<br>'+d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+'</div><div class="timeline-line"></div><div class="timeline-card"><div class="thumb" '+(img?'style="background-image:url(&quot;'+esc(img)+'&quot;)"':'')+'></div><div><strong>'+esc(x.title)+'</strong><small>'+esc(x.board_name||'Board')+(x.last_error?' · '+esc(x.last_error):'')+'</small></div><span class="status-mini '+esc(x.status)+'">'+esc(x.status)+'</span></div><div class="timeline-actions">'+(['scheduled','failed'].includes(x.status)?'<button class="secondary move-pin" data-id="'+esc(x.id)+'">Move</button> <button class="secondary cancel-pin" data-id="'+esc(x.id)+'">Cancel</button>':'')+'</div></div>'}).join('')||'<div class="empty-state">No scheduled Pins yet.</div>';$$('.cancel-pin').forEach(b=>b.onclick=async()=>{if(!confirm('Cancel this scheduled Pin?'))return;try{await api('/api/schedule?id='+encodeURIComponent(b.dataset.id),{method:'DELETE'});await loadSchedule()}catch(e){toast(e.message)}});$$('.move-pin').forEach(b=>b.onclick=async()=>{const item=state.schedule.find(x=>x.id===b.dataset.id),next=prompt('Enter a new local date/time as YYYY-MM-DD HH:MM',new Date(item.scheduled_at).toLocaleString());if(!next)return;const when=new Date(next);if(Number.isNaN(when.getTime())){toast('Invalid date/time');return}try{await api('/api/schedule',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,scheduled_at:when.toISOString()})});await loadSchedule();toast('Scheduled time updated')}catch(e){toast(e.message)}})}
$('#refreshSchedule').onclick=loadSchedule;$('#runDue').onclick=async()=>{if(!state.user){show('settings');return}try{const d=await post('/api/schedule?action=run-due',{});await loadSchedule();toast(d.processed?('Published '+d.processed+' due Pin(s)'):'No Pins are due right now')}catch(e){toast(e.message)}};

async function loadBilling(){try{const d=await api('/api/billing');state.billing=d;$('#billingIntegration').textContent=d.stripeConfigured?'Connected':'Not configured';$('#billingIntegration').className='status-chip '+(d.stripeConfigured?'good':'warn');const plan=d.user?.plan||state.user?.plan||'free';$$('.checkout').forEach(b=>{b.disabled=!d.stripeConfigured||!state.user;b.textContent=b.dataset.plan===plan?'Current plan':'Choose '+b.dataset.plan[0].toUpperCase()+b.dataset.plan.slice(1)});$('#billingNotice').textContent=!state.user?'Sign in to purchase a plan.':!d.stripeConfigured?'Stripe code is ready; add Stripe keys and price IDs to activate checkout.':'Billing is connected.';return d}catch(e){return null}}
$$('.checkout').forEach(b=>b.onclick=async()=>{if(!state.user){show('settings');toast('Sign in first');return}try{const d=await post('/api/billing?action=checkout',{plan:b.dataset.plan});location.href=d.url}catch(e){$('#billingNotice').className='notice error';$('#billingNotice').textContent=e.message}});
const manageBillingBtn=$('#manageBilling');if(manageBillingBtn)manageBillingBtn.onclick=async()=>{if(!state.user){show('settings');return}try{const d=await post('/api/billing?action=portal',{});location.href=d.url}catch(e){toast(e.message)}};
async function syncCheckout(){const q=new URLSearchParams(location.search),session=q.get('session_id');if(q.get('checkout')==='success'&&session){try{const d=await post('/api/billing?action=sync',{session_id:session});toast('Plan activated: '+d.plan);history.replaceState({},'',location.pathname);await loadUser();await loadBilling();show('plans')}catch(e){toast(e.message)}}}

async function loadWebsites(){
  const box=$('#websiteList');if(!box)return;
  if(!state.user){box.innerHTML='<div class="empty-state">Sign in to save a website connection.</div>';$('#websiteStatus').textContent='Sign in required';$('#websiteStatus').className='status-chip warn';return}
  try{
    const d=await api('/api/websites');const sites=d.sites||[];state.sites=sites;
    $('#websiteStatus').textContent=sites.length?(sites.length+' saved'):'Optional';$('#websiteStatus').className='status-chip '+(sites.length?'good':'');
    updateOnboarding();if($('#websiteIntegration')){$('#websiteIntegration').textContent=sites.length?(sites.length+' site'+(sites.length===1?'':'s')+' saved'):'Not connected';$('#websiteIntegration').className='status-chip '+(sites.length?'good':'')}box.innerHTML=sites.map(s=>'<div class="queue-item"><div class="queue-thumb" style="display:grid;place-items:center;background:#f2efff;color:#6847dc;font-weight:900">WP</div><div><strong>'+esc(s.site_name||s.site_url)+'</strong><small>'+esc(s.site_url)+'</small></div><div class="button-row"><button class="text-btn use-site" data-url="'+esc(s.site_url)+'">Use</button><button class="text-btn remove-site" data-id="'+esc(s.id)+'">Remove</button></div></div>').join('')||'<div class="empty-state">No website saved yet.</div>';
    $$('.use-site').forEach(b=>b.onclick=()=>{$('#wpSite').value=b.dataset.url;toast('Website selected — click Load posts')});
    $$('.remove-site').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this saved website connection?'))return;try{await api('/api/websites?id='+encodeURIComponent(b.dataset.id),{method:'DELETE'});await loadWebsites()}catch(e){toast(e.message)}});
  }catch(e){box.innerHTML='<div class="empty-state">'+esc(e.message)+'</div>'}
}
$('#connectWebsite').onclick=async()=>{
  if(!state.user){show('settings');toast('Sign in before saving a website');return}
  const url=$('#websiteConnectUrl').value.trim(),confirmed=$('#websiteConfirmed').checked;
  if(!url){toast('Enter your public WordPress site URL');return}
  if(!confirmed){toast('Confirm you own or are authorized to use this site');return}
  try{const d=await post('/api/websites',{site_url:url,site_name:new URL(url.startsWith('http')?url:'https://'+url).hostname,kind:'wordpress-public',confirmed:true});$('#wpSite').value=d.site_url||url;$('#websiteConnectUrl').value='';$('#websiteConfirmed').checked=false;await loadWebsites();toast('Website saved. You can now load its published posts.')}catch(e){toast(e.message)}
};

async function loadAdmin(){
  if(state.user?.role!=='owner')return;
  try{
    const d=await api('/api/admin?action=status');state.admin=d;
    $('#adminAiStatus').textContent=d.ai.configured?'Configured':'Not configured';$('#adminAiStatus').className='status-chip '+(d.ai.configured?'good':'warn');
    $('#adminEmailStatus').textContent=d.email.configured?'Configured':'Not configured';$('#adminEmailStatus').className='status-chip '+(d.email.configured?'good':'warn');
    $('#adminTextModels').value=(d.ai.textModels||[]).join('\n');$('#adminImageModels').value=(d.ai.imageModels||[]).join('\n');$('#adminDefaultPrompt').value=d.ai.defaultPrompt||'';
    $('#adminTextCost').value=d.ai.costs?.text??1;$('#adminImageLowCost').value=d.ai.costs?.image?.low??4;$('#adminImageMediumCost').value=d.ai.costs?.image?.medium??8;$('#adminImageHighCost').value=d.ai.costs?.image?.high??14;
    $('#adminEmailFrom').value=d.email.from||'';$('#adminUserCount').textContent=(d.users?.length||0)+' users';
    $('#adminUsers').innerHTML=(d.users||[]).map(u=>'<tr><td>'+esc(u.email)+'</td><td><span class="status-chip '+(u.role==='owner'?'good':'')+'">'+esc(u.role)+'</span></td><td>'+(u.email_verified?'<span class="status-chip good">Verified</span>':'<span class="status-chip warn">Pending</span>')+'</td><td><strong>'+fmt.format(Number(u.ai_credits||0))+'</strong></td><td><div class="credit-adjust"><input type="number" value="10" class="credit-delta" data-user="'+esc(u.id)+'"><button class="secondary add-credits" data-user="'+esc(u.id)+'">Apply</button></div></td></tr>').join('')||'<tr><td colspan="5">No users yet.</td></tr>';
    $$('.add-credits').forEach(b=>b.onclick=async()=>{const input=$('.credit-delta[data-user="'+b.dataset.user+'"]'),delta=Number(input?.value||0);if(!delta){toast('Enter a non-zero credit adjustment');return}try{await post('/api/admin?action=credits',{user_id:b.dataset.user,delta,reason:'Owner console adjustment'});await loadAdmin();if(state.user?.id===b.dataset.user)await loadAI();toast('Credits updated')}catch(e){toast(e.message)}});
    await Promise.all([loadBilling(),loadStatus()]);
  }catch(e){toast(e.message)}
}
$('#refreshAdmin').onclick=loadAdmin;
$('#saveAISettings').onclick=async()=>{try{await post('/api/admin?action=save-ai',{api_key:$('#adminOpenAIKey').value,text_models:$('#adminTextModels').value,image_models:$('#adminImageModels').value,default_prompt:$('#adminDefaultPrompt').value,costs:{text:Number($('#adminTextCost').value||1),image:{low:Number($('#adminImageLowCost').value||4),medium:Number($('#adminImageMediumCost').value||8),high:Number($('#adminImageHighCost').value||14)}}});$('#adminOpenAIKey').value='';await Promise.all([loadAdmin(),loadAI()]);$('#adminAiNotice').className='notice success';$('#adminAiNotice').textContent='AI provider settings saved. The key is encrypted and is never sent to workspace users.'}catch(e){$('#adminAiNotice').className='notice error';$('#adminAiNotice').textContent=e.message}};
$('#syncOpenAIModels').onclick=async()=>{try{const d=await api('/api/admin?action=models');if(d.textModels?.length)$('#adminTextModels').value=d.textModels.join('\n');if(d.imageModels?.length)$('#adminImageModels').value=d.imageModels.join('\n');$('#adminAiNotice').className='notice success';$('#adminAiNotice').textContent='Available model IDs loaded from the configured OpenAI account. Review the list and save only models you want customers to use.'}catch(e){$('#adminAiNotice').className='notice error';$('#adminAiNotice').textContent=e.message}};
$('#saveEmailSettings').onclick=async()=>{try{await post('/api/admin?action=save-email',{api_key:$('#adminResendKey').value,from:$('#adminEmailFrom').value});$('#adminResendKey').value='';await loadAdmin();$('#adminEmailNotice').className='notice success';$('#adminEmailNotice').textContent='Email settings saved. New users can receive verification links once the sender domain is accepted by the mail provider.'}catch(e){$('#adminEmailNotice').className='notice error';$('#adminEmailNotice').textContent=e.message}};

async function loadIntegrations(){await Promise.all([loadUser(),loadStatus(),loadAI(),loadWebsites()])}
async function refreshSettings(){await loadUser();await loadStatus()}
$('#disconnectPinterest').onclick=async()=>{if(!confirm('Disconnect Pinterest from this browser?'))return;try{await post('/api/pinterest?action=disconnect',{});state.productionConnected=false;await loadStatus();toast('Pinterest disconnected from this browser')}catch(e){toast(e.message)}};

async function quietDue(){if(!state.user)return;try{const d=await post('/api/schedule?action=run-due',{});if(d.processed)await loadSchedule()}catch{}}
async function init(){setDefaultSchedule();updatePreview();await Promise.all([loadUser(),loadStatus(),loadAI()]);await loadAccount();if(state.productionConnected){await Promise.all([loadAnalytics(true),loadAllPins()])}await loadSchedule();await syncCheckout();const q=new URLSearchParams(location.search);if(q.get('verified')){await loadUser();show('settings');toast('Email verified successfully')}else if(q.get('signup')){show('settings');authMode='signup';$$('.auth-tab').forEach(x=>x.classList.toggle('active',x.dataset.auth==='signup'));$('#authSubmit').textContent='Create account';$('#authPassword').autocomplete='new-password'}else if(q.get('login')){show('settings')}else if(q.get('oauth')){show(q.get('oauth')==='sandbox-connected'?'integrations':'create');if(state.user&&q.get('oauth')==='connected')toast('Pinterest connected. Scheduler authorization saved for this workspace.')}setInterval(quietDue,60000)}
window.addEventListener('resize',()=>{if(state.analytics){drawLine($('#dashboardChart'),state.analytics.series,$('#dashboardChartEmpty'),'IMPRESSION',false);drawLine($('#analyticsChart'),state.analytics.series,$('#analyticsChartEmpty'),state.analyticsMetric||'IMPRESSION',true)}});
init();